-- Import sản phẩm gạch vào Supabase
-- Có thể chạy lại file này nhiều lần: dữ liệu sẽ được cập nhật theo mã sản phẩm.
--
-- Script này hỗ trợ cả trường hợp bảng product_gach_men đã tồn tại nhưng
-- thiếu một số cột. Các cột còn thiếu sẽ được bổ sung tự động.

create table if not exists public.product_gach_men (
  id bigint generated by default as identity primary key,
  name text not null,
  size text not null,
  usage text not null,
  price numeric(14, 2) not null check (price >= 0),
  image text not null,
  surface text,
  material text,
  origin text,
  per_box text,
  warranty text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_gach_men
  add column if not exists external_code text,
  add column if not exists name text,
  add column if not exists size text,
  add column if not exists usage text,
  add column if not exists price numeric(14, 2),
  add column if not exists image text,
  add column if not exists surface text,
  add column if not exists material text,
  add column if not exists origin text,
  add column if not exists per_box text,
  add column if not exists warranty text,
  add column if not exists description text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists product_gach_men_external_code_key
  on public.product_gach_men (external_code);

insert into public.product_gach_men (
  external_code,
  name,
  size,
  usage,
  price,
  image,
  surface,
  material,
  origin,
  per_box,
  warranty,
  description,
  updated_at
)
values
  (
    'CR-6000',
    'Gạch Vân Đá Carrara - STONE',
    '600x600mm',
    'Ốp Tường',
    285000,
    'images/van-da-carrara.svg',
    'Bóng kiếng',
    'Granite nhân tạo',
    'Việt Nam',
    '4 viên/thùng (1.44 m²)',
    '1 năm',
    'Bề mặt vân đá cẩm thạch trắng với đường vân xám mảnh, mang lại cảm giác rộng và sáng cho không gian. Phù hợp phòng khách, sảnh và showroom.',
    now()
  ),
  (
    'MS-300',
    'Gạch Mosaic Xanh Biển',
    '300x300mm',
    'Ốp Tường',
    195000,
    'images/mosaic-xanh-bien.svg',
    'Bóng, chống bám bẩn',
    'Ceramic men bóng',
    'Việt Nam',
    '11 viên/thùng (0.99 m²)',
    '5 năm',
    'Họa tiết mosaic ô vuông nhỏ với nhiều sắc xanh chuyển, tạo điểm nhấn tươi mát. Thường dùng ốp tường nhà tắm, bếp và khu vực bồn rửa.',
    now()
  ),
  (
    'WD-600',
    'Gạch Vân Gỗ Sồi',
    '600x600mm',
    'Lát Nền',
    245000,
    'images/van-go-soi.svg',
    'Nhám mờ, chống trơn R10',
    'Porcelain',
    'Việt Nam',
    '4 viên/thùng (1.44 m²)',
    '10 năm',
    'Vân gỗ sồi tự nhiên in kỹ thuật số, ấm áp như sàn gỗ nhưng bền hơn và không sợ nước. Thích hợp phòng ngủ, phòng khách và quán cà phê.',
    now()
  ),
  (
    'EN-400',
    'Gạch Bông Cổ Điển',
    '400x400mm',
    'Lát Nền',
    320000,
    'images/bong-co-dien.svg',
    'Mờ lì',
    'Xi măng ép nén',
    'Việt Nam',
    '6 viên/thùng (0.96 m²)',
    '8 năm',
    'Họa tiết bông cổ điển xanh – kem theo phong cách Đông Dương, ghép 4 viên tạo thành hoa văn lớn. Đẹp cho ban công, quán ăn, khu vực trang trí.',
    now()
  ),
  (
    'CC-400',
    'Gạch Bê Tông Xám Mờ',
    '400x400mm',
    'Ốp Tường',
    168000,
    'images/be-tong-xam.svg',
    'Mờ, nhám nhẹ',
    'Ceramic',
    'Việt Nam',
    '6 viên/thùng (0.96 m²)',
    '5 năm',
    'Bề mặt giả bê tông xám trung tính theo phong cách tối giản / industrial. Dễ phối với nội thất gỗ và kim loại, hợp ốp tường phòng khách, văn phòng.',
    now()
  ),
  (
    'G-CH-GRANITE',
    'Gạch đá granite',
    '600x600mm',
    'Lát Nền',
    300000,
    'images/uploads/1789368829394-2287076495605217208-777114-1790300166782.jpg',
    null,
    null,
    'Việt Nam',
    null,
    null,
    null,
    now()
  )
on conflict (external_code) do update set
  name = excluded.name,
  size = excluded.size,
  usage = excluded.usage,
  price = excluded.price,
  image = excluded.image,
  surface = excluded.surface,
  material = excluded.material,
  origin = excluded.origin,
  per_box = excluded.per_box,
  warranty = excluded.warranty,
  description = excluded.description,
  updated_at = now();

-- Kiểm tra kết quả sau khi import.
select
  id,
  name,
  size,
  usage,
  price,
  image
from public.product_gach_men
order by id;
